### ISSUE TITLE
Parameter X is Empty

### ISSUE THREAD

**Issue by mwweb** [arslancb/clipbucket#392] opened 2017-07-22 20:28 UTC
I am attempting to import a large video file using the mass uploader (2.8GB). Everything appears to be configured fine.

I've watch the process, and it copies from mass_uploads to temp, then from temp to conversion_queue. At this point, it seems to "crash" with the error of Warning: math:  in /home/domain/public_html/clipbucket/includes/smartyv3/plugins/function.math.php on line 62

Any thoughts on this?

**Comment by fahad-cb** [comment] 2017-07-22 20:37
Warnings are not the cause most oftenly, on which action or how did you
figured out this warning error ?

**Comment by mwweb** [comment] 2017-07-22 20:38
It showed immediate after the import "completed". I got the message that the import was successful, then it showed the error (warning). Let me try it again, and provide a screenshot.

**Comment by mwweb** [comment] 2017-07-22 20:42
Here's the screenshot
![cb-warning](https://user-images.githubusercontent.com/19194012/28494440-92e134e4-6ee3-11e7-8268-09ff4e3f53e1.png)

**Comment by fahad-cb** [comment] 2017-07-22 20:55
alright, is normal video uploading and conversion working fine?

**Comment by mwweb** [comment] 2017-07-22 21:21
Yes. I have imported several other videos. I have just gotten to where there are a few very large files,  greater than 2GB that are throwing this message. If they are smaller than 2GB they appear to work fine.

**Comment by Arman143** [comment] 2017-07-24 05:58
hi,
       i am also getting the same error while activating 30+ videos at once...

**Comment by mwweb** [comment] 2017-07-24 06:50
Good to know that I'm not the only one experiencing this error. Hopefully we'll get an answer and fix soon.

**Comment by mwweb** [comment] 2017-07-30 07:21
Does anyone have any thoughts on this? It may present itself as a warning, but processing does not occur due to this, so it would be more like a fatal error.

**Comment by mwweb** [comment] 2017-07-30 07:54
OK, I recently started branching out coding a few of my own things, which got started looking at the below code, and think I _**MAY**_ have found the cause.

`    foreach ($params as $key => $val) {
        if ($key != "equation" && $key != "format" && $key != "assign") {
            // make sure value is not empty
            if (strlen($val)==0) {
                trigger_error("math: parameter $key is empty",E_USER_WARNING);

                return;
            }
            if (!is_numeric($val)) {
                trigger_error("math: parameter $key: is not numeric",E_USER_WARNING);

                return;
            }
            $equation = preg_replace("/\b$key\b/", " \$params['$key'] ", $equation);
        }
    }
`
This looks to be looking for the length of a parameter, and if the length ==0, then throw the warning. If not, then proceed. 

I looked at the website configurations-->Upload and Conversion Settings, then video conversion at the bottom. The setting for Video Bitrate for HD is empty, or might be able to look at it as 0 (null). I populated the 512000 in it, the same as for standard video bitrate, then saved. I was able to import a video file that was throwing that warning, and it is processing.

However, when I go back to the same area to check again, the field for Video Bitrate for HD (vbrate_hd) is empty once again.

Further, looking through the config table in the DB, I don't see a field for vbrate_hd, which would explain why the field is empty.

**Comment by MacWarrior** [comment] 2017-08-06 20:37
Hi, 
I've experienced this kind of error and I was able to solve it by updating the PHP CLI configuration : 
On Debian 8 : /etc/php5/cli/php.ini
upload_max_filesize = 20000M
max_execution_time = 3600
Then reload apache (Or php-fpm, or anything else)

And of course don't forget to update your "Upload and Conversion Settings" with the same value

**Comment by MacWarrior** [comment] 2017-08-12 10:58
Hi, 

@mwweb : You are right, this config was missing in my configuration, so I manually created it : 
`INSERT INTO {tbl_prefix}config(name, value) VALUES ('vbrate_hd','512000');`
Can't figure out how you got it deleted, in my case the config stay where it is but I am still reproducing the error with a ~11Go (10.93Go, MKV) file

Here is the call stack : 
`#0  smarty_function_math() called at [/home/http/clipbucket-test/cache/4f8b7b9e697aff70a178e5677031a0d45c2984de.file.header.html.php:53]
#1  content_584d47ffd81c57_52106796() called at [/home/http/clipbucket-test/includes/smartyv3/sysplugins/smarty_internal_templatebase.php:182]
#2  Smarty_Internal_TemplateBase->fetch() called at [/home/http/clipbucket-test/includes/smartyv3/sysplugins/smarty_internal_template.php:284]
#3  Smarty_Internal_Template->getSubTemplate() called at [/home/http/clipbucket-test/cache/bc120a504c578f8fdf07f3e43e9e676fb04cb98f.file.body.html.php:35]
#4  content_584d47ffcb9406_25573048() called at [/home/http/clipbucket-test/includes/smartyv3/sysplugins/smarty_internal_templatebase.php:182]
#5  Smarty_Internal_TemplateBase->fetch() called at [/home/http/clipbucket-test/includes/smartyv3/sysplugins/smarty_internal_templatebase.php:377]
#6  Smarty_Internal_TemplateBase->display() called at [/home/http/clipbucket-test/includes/classes/template.class.php:115]
#7  CBTemplate->display() called at [/home/http/clipbucket-test/includes/functions_template.php:39]
#8  Template() called at [/home/http/clipbucket-test/includes/functions_template.php:106]
#9  display_it() called at [/home/http/clipbucket-test/admin_area/mass_uploader.php:200]`

And here is the var_dump($params)
`array(7) {
  ["equation"]=>
  string(21) "x + a + b + c + d + e"
  ["x"]=>
  string(0) ""
  ["a"]=>
  string(0) ""
  ["b"]=>
  int(0)
  ["c"]=>
  int(0)
  ["d"]=>
  int(0)
  ["e"]=>
  string(0) ""
}`

Here is the var_dump($params) where import works : 
`array(7) {
  ["equation"]=>
  string(21) "x + a + b + c + d + e"
  ["x"]=>
  string(1) "0"
  ["a"]=>
  string(1) "0"
  ["b"]=>
  int(0)
  ["c"]=>
  int(0)
  ["d"]=>
  int(0)
  ["e"]=>
  string(1) "0"
}`
As we can see, the difference is on "x", "a" and "e".

This looks to be restricted to the template system and not the conversion or mass upload one

Still investigating...

**Comment by MacWarrior** [comment] 2017-08-12 20:37
Hi, 

I've made a temporary fix for this error : 
https://github.com/MacWarrior/clipbucket/commit/9660ba2dca9e0f51110bd9dc1a3c3c49642fe27a

With this, this error won't appear anymore BUT even if I got a succesfull message from mass upload, my ~11Go file isn't correctly imported/converted

Investigating on this...

**Comment by MacWarrior** [comment] 2017-08-13 11:28
Hi, 

I finally found out why my video wasn't correctly imported and the origin of this error : mysql timeout
By default, the mysql timeout is 300 sec : importing a 11Go file on simple HDD take me ~500sec

I've made some modifications and now it works perfectly : 
https://github.com/MacWarrior/clipbucket/commit/7f60bb834cad140423699d64e896b4c0369912f8

**Closed as completed** 2019-11-18 06:07 UTC
