### ISSUE TITLE
Max video Processes at once issue cb 2.8.1 rc 1

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#119] opened 2016-05-23 05:58 UTC
i have check Max video Processes at once is working fine when you upload 3~4 videos and Max video Processes at once set to 2.. but when you upload about 25 videos the first 2 videos covert fine as Max video Processes at once 2 when one of these 2 videos conversion finished the Max video Processes at once 2 doesn't work and the system start all videos process at once and system is loaded and conversion disturb and the videos never play ...

sorry for my bad English .. but test it

**Comment by sakydev** [comment] 2016-06-03 07:05
duplicate of https://github.com/arslancb/clipbucket/issues/107

**Closed as completed by sakydev** 2016-06-03 07:05 UTC
Labels: bug
